from django.urls import path
from .views import *
urlpatterns = [
    path('', home, name='home'),
    path('dashboard/',dashboard, name='dashboard'),
    path('addteacher/', addteacher, name='addteacher'),
    path('edit_admin_profile/', edit_admin_profile, name='edit_admin_profile'),
    path('addstudent/', addstudent, name='addstudent'),
    path('edit_student_profile/', edit_student_profile, name='edit_student_profile'),
    path('mark_attendance/', mark_attendance, name='mark_attendance'),
    path('view_attendance/', view_attendance, name='view_attendance'),
    path('view_students/', view_students, name='view_students'),
    path('view_teachers/', view_teachers, name='view_teachers'),
    path('edit_teacher_profile/', edit_teacher_profile, name='edit_teacher_profile'),
    path('remove-student/<str:username>/', remove_student, name='remove_student'),
    path('remove_teacher/<str:username>/', remove_teacher, name='remove_teacher'),
    path('attendance/', mark_teacher_attendance, name='attendance'),
    path('view_teacher_attendance/', view_teacher_attendance, name='view_teacher_attendance'),
    path('view_class_students/', view_class_students, name='view_class_students'),
    path('assign_homework/<str:username>/', assign_homework, name='assign_homework'),
    path('view_homework/',view_homework, name='view_homework' ),
    path('notice/', add_exam, name='notice'),
    path('view_notice/', view_notice, name='view_notice'),
    path('post_query/', post_query, name='post_query'),
    path('all_queries/',all_queries, name='all_queries'),
    path('subjects/', subjects, name='subjects'),
    path('addsubjects/', add_subject, name='addsubjects'),
    path('query_detail/<int:query_id>/', query_detail, name='query_detail'),
    path('funds/', funds, name='funds'),
    path('viewsalary/',view_salary, name='viewsalary'),
    path('salary/',salary, name='salary'),
    path('pay_salary/<str:username>/',pay_salary, name='pay_salary'),
    path('pay_fee/',pay_fee, name='pay_fee'),
    path('view_fee/',view_fee, name='view_fee'),
    path('approvefee/<int:id>/', approvefee, name='approvefee'),
    path('logout/', logout, name='logout'),
]