# Generated by Django 5.0.4 on 2024-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='city',
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='Teaceher', max_length=32),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.FileField(default='', upload_to='Teacher/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='Student', max_length=32),
        ),
    ]
