# Generated by Django 5.0.4 on 2024-05-18 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0002_loginuser_remove_teacher_city_teacher_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['date', 'student']},
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='created',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='updated',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asms_app.student'),
        ),
    ]
