# Generated by Django 5.0.4 on 2024-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0003_alter_studentattendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acedemiaadmin',
            name='utype',
            field=models.CharField(default='Admin', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='utype',
            field=models.CharField(default='Student', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='utype',
            field=models.CharField(default='Teacher', max_length=20),
        ),
    ]
