# Generated by Django 5.0.4 on 2024-05-19 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0006_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
