# Generated by Django 5.0.4 on 2024-05-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0007_alter_exam_examtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='repliedby',
            field=models.CharField(default='', max_length=30),
        ),
    ]
