# Generated by Django 5.0.4 on 2024-05-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0008_reply_repliedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='repliedby',
            field=models.CharField(max_length=30),
        ),
    ]
