# Generated by Django 5.0.4 on 2024-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0010_alter_exam_examdate_alter_subjects_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subclass',
            field=models.CharField(max_length=3),
        ),
    ]
