# Generated by Django 5.0.4 on 2024-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0011_alter_subjects_subclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='due',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
    ]
